[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$OutputFile,
    [Parameter(Mandatory = $true)][string]$PayloadDirectory,
    [Parameter(Mandatory = $true)][string]$ScriptDirectory,
    [Parameter(Mandatory = $true)][string]$RepositoryRoot
)

$ErrorActionPreference = 'Stop'

$resources = @(
    [pscustomobject]@{ Id = 101; File = Join-Path $PayloadDirectory 'am-exclusive-broker.exe' }
    [pscustomobject]@{ Id = 103; File = Join-Path $PayloadDirectory 'am_exclusive_media_control.exe' }
    [pscustomobject]@{ Id = 104; File = Join-Path $PayloadDirectory 'am-exclusive-hook.dll' }
    [pscustomobject]@{ Id = 105; File = Join-Path $PayloadDirectory 'am-exclusive-ui.dll' }
    [pscustomobject]@{ Id = 106; File = Join-Path $PayloadDirectory 'am-exclusive.ini' }
    [pscustomobject]@{ Id = 107; File = Join-Path $ScriptDirectory 'Install-Mod.ps1' }
    [pscustomobject]@{ Id = 108; File = Join-Path $ScriptDirectory 'Uninstall-Mod.ps1' }
    [pscustomobject]@{ Id = 109; File = Join-Path $ScriptDirectory 'Register-Companion.ps1' }
    [pscustomobject]@{ Id = 110; File = Join-Path $ScriptDirectory 'Uninstall.cmd' }
    [pscustomobject]@{ Id = 111; File = Join-Path $RepositoryRoot 'LICENSE' }
    [pscustomobject]@{ Id = 112; File = Join-Path $RepositoryRoot 'THIRD_PARTY_NOTICES.md' }
)

foreach ($resource in $resources) {
    $resource.File = [IO.Path]::GetFullPath($resource.File)
    if (-not (Test-Path -LiteralPath $resource.File -PathType Leaf)) {
        throw "Cannot generate setup resources before payload exists: $($resource.File)"
    }
}

$parent = Split-Path -Parent ([IO.Path]::GetFullPath($OutputFile))
New-Item -ItemType Directory -Path $parent -Force | Out-Null

$lines = @(
    '// Generated by Generate-SetupResources.ps1. Do not edit.'
    '#include <windows.h>'
    ''
)
foreach ($resource in $resources) {
    # Forward slashes are accepted by rc.exe and avoid treating a Windows path
    # separator as an escape while the resource compiler parses the string.
    $rcPath = $resource.File.Replace('\', '/')
    $rcPath = $rcPath.Replace('"', '\"')
    $lines += "$($resource.Id) RCDATA `"$rcPath`""
}

$utf8 = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllText([IO.Path]::GetFullPath($OutputFile),
                        ($lines -join [Environment]::NewLine),
                        $utf8)
