#pragma once

#define AMMOD_RESOURCE_BROKER 101
#define AMMOD_RESOURCE_MEDIA_CONTROL 103
#define AMMOD_RESOURCE_HOOK 104
#define AMMOD_RESOURCE_UI 105
#define AMMOD_RESOURCE_INI 106
#define AMMOD_RESOURCE_INSTALL 107
#define AMMOD_RESOURCE_UNINSTALL 108
#define AMMOD_RESOURCE_REGISTER_COMPANION 109
#define AMMOD_RESOURCE_UNINSTALL_CMD 110
#define AMMOD_RESOURCE_LICENSE 111
#define AMMOD_RESOURCE_THIRD_PARTY_NOTICES 112
